---
---
= About
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-next: <<contact.adoc#,contact>>

nav::[]

I’m an electrical engineer about to graduate, but I have a couple of years of part-time working experience already.
My education is mainly on power systems, but my interest is far wider than the grid and its components.
Systems, interfaces and processes get me excited, all the way from the hardware to software applications and the human effort.
I have satisfied my interest for a great deal by observing the communities around free software and free hardware since both provide great resources on both practical and theoretical aspects of technology.
Currently my part-time job is in the field of energy management systems, where I’m involved in an effort to provide a common interface to the various energy management systems available in order to speed up application development.
My part-time graduation concerns fault location in low voltage systems, based on measurements in infrastructure, thus potentially providing fault information even before the engineer is on site.

nav::[]
