// --
// tags: [Digital freedom, Free software]
// --
= Circumventing Google on mobile
:author:   Nico Rikken
:revdate:  2014-11-03
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

Nowadays there are many ways to circumvent Google’s services for mobile, which is especially important to Android users who would like to take the next step in link:https://fsfe.org/campaigns/android/android.en.html[freeing their Android]. There are other link:https://mykolab.com/[email providers], other link:http://owncloud.org/[PIM syncing services] and other link:https://f-droid.org/[application distributors]. However I would assume that sometimes a couple of non-free applications might be holding users back from freeing their Android, for instance because no free alternative is available or because their friends are tied in a non-free environment. Luckily the link:http://www.jupiterbroadcasting.com/70397/opensuse-13-2-review-linux-action-show-337/[Linux Action Show] made me aware of link:https://codingteam.net/project/googleplaydownloader[GooglePlayDownloader] a project which enables the user to download .apk files from the Google Play Store whilst circumventing the logging and syncing required by Google. This is of course a cat and mouse game, with the associated projects reverse-engineering the API’s and store navigation to keep track of this moving target. With most software creators targeting just the Google Play Store for Android applications, this is a valuable addition to the set of tools that aid in freeing mobile users.

nav::[]
