// --
// tags: [Free software]
// --
= Open furniture
:author:   Nico Rikken
:revdate:  2014-08-20
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

During the last decades a slight change has occurred in the field of furniture, with the rise of modular furniture. Modular furniture has great benefits, since it can often be rearranged to fit changing needs, allowing people to hold on to their furniture much longer. Examples of such systems are Ikea Pax and Besta, link:http://lundia.com/[Lundia], and my personal favorite link:https://www.vitsoe.com/[Vitsœ]. I do however believe that the current situation is somewhat unfortunate, since the different interfaces result in a system lock-in which limits the available components and the flexibility of the system. This therefore leaves room for improvement, giving rise to my idea.

By getting the implicit interfaces of furniture and the compatibility of the various components documented in a wiki-format, people might make a more conscious decision for a particular system which would contribute to the overall time of use. I imagine this covering for instance the panel sizes, the measurements between the various screw-holes and the similarity between systems. Furthermore I’m hoping that such information will assist companies and individuals to create additional furniture components that are compatible with existing systems in order to aid consumers in utilizing their system. It might even give rise to converters that will bridge the gap between systems. Exemplary for working with existing standards are the 3D-printable universal construction kit link:http://www.thingiverse.com/search/page:1?q=universal+construction+kit[adapters].

nav::[]
