// --
// tags: [Free software, Productivity]
// --
= Down the path with Emacs
:author:   Nico Rikken
:revdate:  2014-08-18
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

Just about a year ago I started using link:https://en.wikipedia.org/wiki/Emacs[Emacs] and I’ve now come to the conclusion that it is about time to get out of the Emacs-world.

I used to make use of link:http://zim-wiki.org/[Zim] and link:http://gtgnome.net/[GTG] for both my notes and tasks, but as I was using ever more shortcuts, I was keen on employing more advanced tools, especially with a lot of conversion formats in order to liberate my content. After an extensive search I started using Emacs link:http://orgmode.org/[Org mode]. I must admit that Org mode is brilliant and very powerful. Adopting Org mode as a non-Emacs user meant I had to learn the most common Emacs shortcuts and get a sense of the considerations underlying Emacs. Having gotten up to steam, it is a brilliant way of managing notes and tasks intertwined, living in a flat file system. Being able to create overviews of all the different tasks allowed advanced overviews to be generated and allowed me to test various management styles like link:https://en.wikipedia.org/wiki/Getting_Things_Done[GTD] and link:https://en.wikipedia.org/wiki/Kanban[Kanban]. By far the most powerful example of using Org mode was about half a year in: I had only a couple of days at an external company to work out a project outline. Being able to keep notes and tasks with blinding speed was already incredible, but being able to export a draft outline to both a neatly styled link:https://en.wikipedia.org/wiki/LaTeX[LaTeX] report and LaTeX presentation was a great time-saver which made quite an impression.

Spending a lot of time in Emacs already, it only seemed logical to point more activities towards Emacs, which is the eventual consequence of such a tightly integrated editor with all its versatility. It didn’t took long for me to strictly use Emacs for my writing, coding, news reading and even browsing. Emacs really became my operating system, just the way as it has been joked by the community.

Emacs however isn’t an operating system. And Emacs isn’t a windows manager either. Emacs is just a legacy editor with many powerful modes which can be tailored to suit a lot of use-cases. Having adopted Emacs as my main tool, I became quite aware of its limitations. Limitations which aren’t around when using other programs for the job. Also the integration of Emacs with other programs wasn’t very good. Copying content from Emacs to other programs often required another editor like gedit to bridge the gap.

Now I’m steadily moving my activities and content back to my favorite GUI applications, which have a large user base and are dedicated to a particular set of tasks.

In retrospect I would describe Emacs as Swiss army knife combined with a pile of wood: you’ll be able to achieve a lot with the tool alone and by creating your own set of tools from to wood you can achieve even more. Nowadays there are however more tailored tools for the various jobs and making everything yourself just seems pointless.

nav::[]
