// ---
// tags: [free software, Digital Freedom]
// ---
= Fairphone back to the drawing board
:author:   Nico Rikken
:revdate:  2015-03-23
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>
// :nav-prev: <<2016-07-21-starting-a-blog-in-asciidoc.adoc#,Starting a blog in asciidoc>>
:nav-next: <<2015-05-05-my-c720p-upgrade-to-freedom.adoc#,My C720P upgrade to freedom>>

nav::[]

Previously I’ve shared my link:http://nicorikken.eu/blog/ubuntu-calling-for-freedom/[thoughts and concerns] on freedom in mobile operating systems. The link:http://fairphone.nl/[Fairphone] project unfortunately has a bad reputation in this area. Not because they don’t care, but because they failed to deliver on this promise in their first version. Other people involved in open hardware design for mobile devices saw link:http://lists.phcomp.co.uk/pipermail/arm-netbook/2015-January/010402.html[it coming] as they’ve been struggling with exactly the same issue for many years already. Especially for them it shouldn’t have been a surprise that a perfectly fine hardware platform would link:http://www.fairphone.com/2014/12/09/our-approach-to-software-and-ongoing-support-for-the-first-fairphones/[be kept] from future firmware updates.

But as in any process of innovation, a new version allows for improvements. And so will a new upcoming version of the Fairphone. For months the Fairphone has featured several link:https://forum.fairphone.com/t/poll-future-fairphone-os-development/157[lengthy threads] discussing alternative, generally more free operating systems. As I tried to state with a link:https://forum.fairphone.com/t/poll-future-fairphone-os-development/157/191[lengthy forum post] there are multiple interest in strong conflict with each other. So even whether there will be multiple OS flavours or one for all customers is not yet decided. The great news however is that the Fairphone team have taken on this challenge, big time! I’ve had some email conversations with link:http://www.fairphone.com/author/kees-jongenburger/[Kees Jongenburger] and link:http://www.fairphone.com/author/joe/[Joe Mier] regarding further plans and options. But more importantly, they went link:http://www.fairphone.com/2015/03/17/looking-for-an-open-operating-system-at-mobile-world-congress-2015/[looking for alternatives] at the Mobile World Congress. Over the course of the next months the plans will be finalized, so I’d like to encourage anybody with relevant information to contribute to the discussions. Let’s make the next Fairphone far more fair.

nav::[]
