---
tags: [Digital freedom, Free software]
---
= The fun of free software
:author:   Nico Rikken
:revdate:  2014-11-21
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

Despite running Linux for over 6 years now, I just recently converted my machine to link:https://en.wikipedia.org/wiki/Debian#Distributions[Debian Testing]. My initial reason for running Testing was to obtain newer versions of packages I value, like the link:http://www.gnome.org/[GNOME] desktop environment, the link:https://wiki.gnome.org/Apps/LaTeXila[LaTeXila] editor, and the link:http://www.scilab.org/[Scilab] simulation software. Therefore right out of the box it was very satisfying getting to experience the progress that had been made since the last Debian Stable release. However in Scilab I experienced the problem of graphs not displaying as they should. Of course I filed a link:https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=767224[bug report] and by creating a workaround (writing svg images) I was able to continue business as usual. Now what I wasn’t expecting, is the level of excitement I got from having a bug that was bothering you finally solved. When I upgraded my packages today I found out that this specific bug has been fixed and even though it was a minor issue, it is amazing that all the people in patching the software and releasing it cared about my issues, and that so many other users will benefit from this patch as well. Not just seeing the larger updates but especially seeing the smaller improvements does shed a different light on software development in the free software community and I’d like to think it is very addictive, especially for the more technical users, to continually be supplied with small improvements.

nav::[]
