---
tags: [Other]
---
= Scalability of higher laws
:author:   Nico Rikken
:revdate:  2014-09-19

In his book link:https://en.wikipedia.org/wiki/Walden[Walden] Henry David Thoreau writes about ‘higher laws’. Specific examples he state regard hunting and eating. Even though his statements intuitively seem truthful, the arguments don’t scale very well to modern society. Specifically he shares his view that in order for a personal to mentally ‘grow up’ he’d best practice the less higher practices (like hunting) and learn by experience that this practice isn’t ‘high’ enough. Taking this example, everybody should first make a lot of ‘mistakes’ in order to develop to a better self. However the society is built upon it’s social values and norms and on its technology. People can depart from the learnings of other people, even those who lived decades ago. In society the scientific method for example is regarded as normal and so is taking care of the environment. As for technology, people wouldn’t buy inefficient (although maybe powerful) cars now that fuel-efficient motors are available. The amount of ‘growing up’ for the more basic aspects of life isn’t what it used to be. Considering this growing up still seems possible and desirable, although it’s starting point is the current set of practices of society and technology.
