---
tags: [Digital freedom]
---
= A minimum level of sharing capabilities
:author:   Nico Rikken
:revdate:  2014-08-17
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

Lately it has struck me how the sharing of content we were use to, are now slowly being taken away from us, without most of us noticing. Remember how anyone was able to lend out their books, CD’s and DVD’s, even just a couple of years ago? Today there is a totally different paradigm. More and more the content is becoming strictly contained in the domains of the service providers via forms of link:https://en.wikipedia.org/wiki/Digital_rights_management[DRM]. Streaming services like link:https://en.wikipedia.org/wiki/Spotify[Spotify] and link:https://en.wikipedia.org/wiki/Netflix[Netflix] keep their content stored online and programs like link:https://en.wikipedia.org/wiki/Itunes[iTunes] and link:https://en.wikipedia.org/wiki/Adobe_Digital_Editions[Adobe Digital Editions] make sure that even the local storage is in the hands of the service provider. Now, this movement in itself is not as bad as it might seem, since you could for example still lend somebody the account credentials or share an e-reader. However simultaneously there is trend towards a strong tie between devices and their users. Just imagine swapping smartphones with a friend for a week so you can enjoy each others e-books, it is unthinkable since that smartphone is tied to your email, your apps, your passwords, your phone number and your other media. Spending a little money on buying an e-book rather than sharing devices is therefore the only sane option. Apple currently seems at the forefront of pushing this paradigm of devices belonging to only a single user by focusing on a seamless experience between devices and by linking it all to your link:https://en.wikipedia.org/wiki/Apple_id[Apple ID]. It is not without reason that better content sharing options were most-requested and recently adopted in the form of link:https://www.apple.com/ios/ios8/family-sharing/[Family Sharing]. However the scope of lending out content is still far more limited than it ever was in the previous decades.

Apart from sharing, we in Europe have also agreed on several rights people have for legally copying content. In the Netherlands this mainly entails making a private copy of legally distributed content and making a private copy for studying purposes. Depending on the media copying was done with a photo-copier, an audio tape recorder or a video tape recorder. With content being restricted end-to-end, the only real way of making a copy seems to be at the side of the human accessing it. This means recording the audio using a microphone, recording the video using a video-camera and copying an e-book with a camera or photo-copier. Granted, other methods exist but these mainly require someone technical to circumvent these restrictions. So the conclusion to be made, is that with the digital revolution, copying content in the way you are entitled to by law has become harder and not easier.

How can it be that as a society we have agreed on what a person should and should not be able to do with content in terms of lending and copying, but that the main content distributors and their technology are not supporting these rights in any way? Since ultimately the desire for content outweighs the ethical considerations for most consumers, it is up to the governments and related institutions to demand the implementation of the level of freedom we have agreed on. Since the law is the ultimate restriction, code needn’t be and shouldn’t be more restrictive than the law.

nav::[]
