---
tags: [Digital freedom, Free software]
---
= Why EOMA68 will advance both free software and free hardware
:author:   Nico Rikken
:revdate:  2014-12-24
:navicons:
:nav-home: <<../index.adoc#,home>>
:nav-up:   <<index.adoc#,posts>>

nav::[]

If you’re not familiar with link:http://elinux.org/Embedded_Open_Modular_Architecture/EOMA-68[EOMA68], it’s an open electronic interface standard specifically designed to support the development of small computing devices built-up of free hardware and free software. It is mostly known for it’s involvement in the link:http://liliputing.com/2013/11/improv-is-a-75-modular-arm-based-computer-core-eoma-68.html[third attempt] for creating the KDE-tablet, known as the link:http://www.slashgear.com/spark-plasma-active-7-inch-tablet-revealed-set-to-take-on-android-30211264/[Spark tablet] and the link:http://liliputing.com/2013/02/vivaldi-kde-open-source-linux-tablet-gets-new-hardware-could-launch-this-spring.html[Vivaldi tablet]. In this project it was found that it is impossible to rely on the continuity of hardware specifications by Asian electronic vendors. If your goal is to develop a software stack, targeting changing hardware will consume most of the development resources, rendering the project useless. So it became clear that control of the hardware is very important in the fast-paced world of embedded and mobile computing. The EOMA68 standard is an important stepping stone in this regard, because it defines a strict interface between the processing board which includes the main component drivers and the board it is inserted into to provide all the necessary interfaces for the link:http://rhombus-tech.net/community_ideas/[final use-case]. This means that the processing boards can be produced at sufficient volumes to enable the desired control over the internal components and thus the free software support. The devices interfacing with the processing boards might be subject to electronic changes, but due to the EOMA68 abstraction, the impact on the software stack will at the very least exclude the basic working of the operating system.

So in this way EOMA68 enables the development of free software for this kind of hardware, but it also increases the ability to design free hardware. If a more free option for chips becomes available, the only step involved for freeing the end-user devices is to develop and build new processing boards. This is far easier of a task than incorporating all the interfaces (like screen drivers) and also the production count can be higher since it is more widely applicable. Also in the process of development the new processing board, it could be tested on the existing EOMA68 platforms without having to develop specific setups. For instance new processing boards can be beta-tested by swapping new cards around between people having EOMA68 compatible devices. Likewise new EOMA68 platforms can be developed and tested by comparing the performance between different processing platforms. So say a driver is functional on a general 64-bit architecture, the driver on the other architecture can be tested to produce the same results, all without creating specific setups for each hardware component.

Then in addition the standard brings the advantage of upgradeable hardware and even shared hardware to the table. The link:http://elinux.org/Embedded_Open_Modular_Architecture#PCMCIA_form-factor[PCMCIA-based boards] can be handled by consumers without risking ESD-issues and the interface allows repeated plugging and unplugging without deprecating the contacts. So if your laptop gets slower you just buy a new board for it. And by switching your boards around like a domino-game you can consequently upgrade your netbook, tablet, router or even your smartphone as well. You can leave the now spare processing board on the shelf as a back-up or buy an additional platform to fill another need. This type of upgrading reduces cost and e-waste. Another option would be to have true continuity by carrying a processing board and changing its interfaces depending on the need. You could even change to device with another screen type if you would like to work out in the sun or you could use the built-in connectors of the processing board to watch your holiday pictures at a friend’s place.

So how can you get on board with this? Well, there is a link:https://www.crowdsupply.com/eoma68/micro-desktop[crowdfunding campaign] link:http://lists.phcomp.co.uk/pipermail/arm-netbook/2014-November/010300.html[about to launch] in order to bootstrap this new paradigm. And just as this system enables, a new and more free processing board is link:http://rhombus-tech.net/icubecorp/IC1T/news/[already in development].

nav::[]
