---
tags: [Digital freedom, Free software]
---
= Ubuntu calling freedom
:author:   Nico Rikken
:revdate:  2015-02-14

So far the flash sales of the first Ubuntu phone link:http://www.omgubuntu.co.uk/2015/02/bq-ubuntu-phone-goes-sale-next-week-e169-meizu-device-coming-soon[by Bq] has been link:http://www.omgubuntu.co.uk/2015/02/96735[sold out], and certainly not without a reason: the Ubuntu phone holds great promises for both the users and the development community. On the FSFE link:https://mail.fsfeurope.org/mailman/listinfo/discussion[Discussion mailinglist] I already gave a quick and general link:http://mail.fsfeurope.org/pipermail/discussion/2015-February/010456.html[overview] mostly based on a recent Linux Unplugged link:http://www.jupiterbroadcasting.com/77087/ubuntu-calling-lup-79/[podcast], and so in this post I’d like to revisit my comments with a focus on freedom, as this is lacking in link:http://opensource.com/business/15/2/what-ubuntu-phone-could-mean-open-source[other] articles. One word of caution though, I haven’t yet read formal documents or code, so all listed info is second-hand.

First off, embedded devices are difficult, and phones in particular are hard, like Fairphone for instance has link:https://blogs.fsfe.org/pboddie/?p=802[come to find]. The problem with phone-hardware in general, is the fact that a build is needed for a specific phone since auto-discovery of peripherals like on a regular computer is missing. Add to that the fact that electronics are developed more rapidly than free drivers an be developed, as was the case for the link:http://nicorikken.eu/blog/why-eoma68-will-advance-both-free-software-and-free-hardware/[Vivaldi tablet]. So unless you have a say in the electronics, and allow a non-signed bootloader, it is very hard and especially time-consuming to develop this lowest layer as free software. and that is also why project like link:http://neo900.org/[Neo900] and link:http://projects.goldelico.com/p/gta04-main/[GTA04] exist. One of the added benefits the GTA04 offers, is that the modem is physically separated from other processors, as the modem implementation is locked-down by law. This is about as free software supporting as free hardware designs can get, but this freedom comes at a cost in performance and money, thus requiring plenty of commitment to become a reality.

So in order to actually ship a product, using non-free designs and chips will be the default option, like Ubuntu did in this instance. In order to get a kernel running the device-specific board support package offers the prerequisites needed to boot the Linux kernel. But rather than modifying the Linux kernel and building a tightly integrated software stack for a particular device, as is the case for Android, link:https://en.wikipedia.org/wiki/Ubuntu_phone[Ubuntu Phone] separates the software stack in two separate layers: a device-specific part and a Ubuntu-part. This separation is ingenious and brings great benefits.

By having a separate Ubuntu-part, this can be updated in the future, without having to do revisions on the device-specific part, thus allowing all models to stay up to date with the newest Ubuntu, and thus avoiding both the platform segregation of Android and the limited number of firmware updates like on iOS. Users can thus still get security fixes and the features newer applications might rely on. Also regarding this part, it would be possible to run a different top layer for a specific mobile operator, or run a different interface on top of this Ubuntu separation layer. I haven’t looked into this layer, but ideally it should be a clean and stable in order to allow others to adopt it.

Likewise the bottom part can be swapped. For instance an Ubuntu Phone port was made to the link:https://wiki.ubuntu.com/Touch/Devices#line-45[Nexus 5], which was done by building the necessary but limited hardware support and offering the separation layer. Due to the additional separation, this port will be able to keep up with firmware updates, and so all additional development efforts can go towards improving the device-specific part rather than keeping up with firmware versions. Depending on the required complexity of this device-specific layer, porting additional devices is relatively easy and particularly fruitful as it can remain nearly a one-time effort.

I’m not aware how free the Ubuntu-part is, although I assume this would be in line with other Ubuntu distributions where it mostly adheres to your needs for freedom. The interface is based on Qt5 and is very supportive of HTML5 applications. In this way mobile applications would be able to run on the Ubuntu desktop in the same matter, offering a great convergence solution. Also it is supportive of efforts being made to put forward HTML5 applications for a run-everywhere solution. There is no policy which requires applications to be free, so you can install all kinds of applications, of which a link:https://appstore.bhdouglass.com/apps[long list] is already available. Users are able to sideload applications, avoiding the dependence on an appstore, which is probably the reason why no appstore was launched by Ubuntu just yet. Of no less importance, it link:https://www.youtube.com/watch?v=TShKZLeZzWE[seems] to be well designed and offer great usability.

One somewhat overlooked part, is the availability of link:https://www.youtube.com/watch?v=vm2NUl1_kSA[scopes]. They aren’t as much overlooked in functionality, but rather in philosophy. Android and iOS have recently realized that apps can be complementary and it is up to the firmware to provide the integration. This can be news and weather, but more recently health and home automation seem relevant as well. The fact that scopes can either work with local data or on the internet but not both, respects the capabilities of the device and prevents unwanted data transmission. More importantly by offering aggregated scopes, you can create a locally generated view. This adheres to the vision of a web which is decentralized rather than centralized and in which each computer has many outgoing connections.

Of course the big elephant in the room is that the phone ties into the Ubuntu ecosystem and so convergence would be best between the Ubuntu phone and the Ubuntu desktop, and likewise it would bring a boost to the Ubuntu store, Ubuntu link:http://www.ubuntu.com/things[Snappy Core] and presumably to cloud services. So what if Ubuntu would be the next big platform? Well, it would bring a very free firmware which is very friendly to porting devices, it would encourage development in HTML5 and Qt, it would encourage more decentralized applications, it would enable development of the Ubunthu phone itself, and it would put a great alternative next to the Google-ized Android and other systems.

Either way, I nearly bought one but I just missed out by the flash-sale. I’d strongly consider ordering one, because I believe this stack is much more freedom-respecting than Android. More frustrating my perfectly fine phone is still on Android 2.2 with a lack of application support and a whole load of known bugs. I haven’t looked deep enough into Jolla or Tizen to judge them. There are many known improvements available to be adopted, both in hardware, firmware and the available applications. Currently however this seems to be a great phone, with a great software platform, which is another stepping stone in the right direction.
